# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='departure',
            new_name='departure_city',
        ),
    ]
