# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0003_tourcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcomponent',
            name='component_type',
            field=models.CharField(choices=[('ACT', 'Activity'), ('TRA', 'Transport'), ('HOU', 'Hotel')], default='ACTIVITY', max_length=17),
        ),
        migrations.AddField(
            model_name='tourcomponent',
            name='tour',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='beyt.Tour'),
        ),
    ]
