# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0005_auto_20160820_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourcomponent',
            name='component_type',
        ),
    ]
