# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0007_remove_tourcomponent_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcomponent',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beyt.Tour'),
        ),
    ]
