# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0011_auto_20160821_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beyt.Activity'),
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
