# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0012_auto_20160821_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beyt.Activity'),
        ),
    ]
