# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0013_auto_20160821_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='arrival_city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='arrival_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='departure_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
