# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0014_auto_20160821_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200, null=True)),
                ('details', models.CharField(max_length=200, null=True)),
                ('streetAddress', models.CharField(max_length=200, null=True)),
                ('postalCode', models.CharField(max_length=200, null=True)),
                ('addressLocality', models.CharField(max_length=200, null=True)),
                ('addressRegion', models.CharField(max_length=200, null=True)),
                ('addressCountry', models.CharField(max_length=200, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=20, null=True)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=20, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.RemoveField(
            model_name='tour',
            name='arrival_city',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='departure_city',
        ),
    ]
