# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0015_auto_20160821_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='arrival_location',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='departure_location',
        ),
    ]
