# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0016_auto_20160821_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='arrival_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_location', to='beyt.Location'),
        ),
        migrations.AddField(
            model_name='tour',
            name='departure_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_location', to='beyt.Location'),
        ),
    ]
