# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0018_auto_20160821_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='hotelPickup',
            new_name='hotelPickupAccepted',
        ),
    ]
