# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0019_auto_20160821_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
