# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0021_auto_20160821_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatelocation',
            name='type',
            field=models.CharField(default='aa', max_length=2),
        ),
        migrations.AddField(
            model_name='translatetour',
            name='type',
            field=models.CharField(default='aa', max_length=2),
        ),
    ]
