# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0022_auto_20160821_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='touractivity',
            options={'verbose_name_plural': 'Tour activities'},
        ),
        migrations.AlterModelOptions(
            name='translatelocation',
            options={'verbose_name_plural': 'translatelocations'},
        ),
        migrations.AlterField(
            model_name='translatelocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='beyt.Location'),
        ),
        migrations.AlterField(
            model_name='translatetour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='beyt.Tour'),
        ),
        migrations.AlterField(
            model_name='translatetour',
            name='type',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
