# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0023_auto_20160821_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatetour',
            name='type',
            field=models.CharField(choices=[('1', 'Default'), ('2', 'Human'), ('3', 'Machine')], default='1', max_length=2),
        ),
    ]
