# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0024_auto_20160821_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='defaultLanguage',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='title',
        ),
    ]
