# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0025_auto_20160821_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='title',
            field=models.CharField(default='Visite de Paris', max_length=200),
        ),
    ]
