# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0026_tour_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
