# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0027_auto_20160821_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='title',
        ),
    ]
