# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0029_auto_20160821_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touractivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='beyt.Activity'),
        ),
        migrations.AlterField(
            model_name='touractivity',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='beyt.Tour'),
        ),
    ]
