# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0030_auto_20160821_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='sizeMax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='sizeMin',
            field=models.IntegerField(null=True),
        ),
    ]
