# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beyt', '0031_auto_20160821_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
